# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
script: echo "I am commons"

# Perform steps after compilation/test success
after_success:
  # Get files for use with build, namely the custom Maven settings.xml
  - "git clone https://github.com/flow/travis-ci-resources.git target/travis"
  # Check if commit is not a pull request, if repo is official, and branch is master, generate and deploy artifacts and reports
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/flow-commons ]] && [[ $TRAVIS_BRANCH == master ]] && mvn javadoc:jar source:jar cobertura:cobertura coveralls:cobertura -DserviceJobId=$TRAVIS_JOB_ID deploy --settings target/travis/settings.xml"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/2047/a69bTjQUT2w1oZF7h23q0nGU

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "KSYs2gR7UNxJd6YzcZpaJvumZuVIS3e1hcs0cFRhEi+lIBQ0AEScas9tUxAkUFRlmZmsKXv205HjDVTeWn//LXceVDrKBsXqurcH4SIji7tfEXKsv8QZ6ipO18Zt4SxG3Mg38XMRtf3SR9BzFJDLzWfdAqSOrozPtdkYQhn8E04="
    - secure: "SFZnSndb4c+1H/XCg9l4ovcJki8mEknXGwfjsL+lUMaaYG6qk0lBOS9GHXkEeQXlE8JD0IKSUSPzu38pKjXpoML28/4sLrQZSZZ+lBZOvRbI//Fcw8gx7KLXhQt9jpmYS3sUbcWAQstl9zGiKPjbQHeu3A+BgEpiUgtWqsixxsU="
